<?php
/**
 * @file
 * Code for the UG Webform feature.
 */

include_once 'ug_webform.features.inc';


/**
 * Alter the list of available Webform components.
 *
 * @param $components
 *   A list of existing components as defined by hook_webform_component_info().
 *
 * @see hook_webform_component_info()
 */
function ug_webform_webform_component_info_alter(&$components) {
  // Completely remove a component.
  unset($components['date']);
  unset($components['time']);
  unset($components['grid']);
}

/**
 * Implementation of hook_form_alter().
 */
function ug_webform_form_alter(&$form, $form_state, $form_id) {
  if (user_is_anonymous() && strrpos($form_id, 'webform_client_form_', -strlen($form_id)) !== false) {
    $form['captcha'] = array( '#type' => 'captcha' );
  }
}

