; This file was auto-generated by drush make
core = 7.x
api = 2

projects[auto_nodetitle][version] = "1.0"
projects[auto_nodetitle][patch][] = "https://www.drupal.org/files/issues/auto_nodetitle-dont_double_escape_titles-565922-39-against-1.0-stable.patch"

projects[ctools][version] = "1.11"
projects[ctools][patch][] = "https://www.drupal.org/files/issues/views_panes-more_link_text-1000146-25.patch"

projects[calendar][version] = "3.5"
projects[calendar][patch][] = "https://www.drupal.org/files/issues/calendar-no_results-2489146-1-D7.patch"

projects[captcha][version] = "1.3"

projects[ckeditor][version] = "1.17"

projects[ckeditor_link][version] = "2.4"

projects[crumbs][version] = "2.5"

projects[date][version] = "2.9"

projects[devel][version] = "1.5"

projects[diff][version] = "3.2"

projects[ds][version] = "2.14"

projects[ds_bootstrap_layouts][version] = "3.1"

projects[entity][version] = "1.8"

projects[entityreference][version] = "1.2"
projects[entityreference][patch][] = "https://www.drupal.org/files/issues/entityreference-use-tokens-2010898-175.patch"

projects[features][version] = "2.10"

projects[field_collection][version] = "1.0-beta11"

projects[field_group][version] = "1.5"

projects[field_permissions][version] = "1.0"

projects[field_validation][version] = "2.6"

projects[fontawesome][version] = "2.6"

projects[hide_submit][version] = "2.4"

projects[panels][version] = "3.8"

projects[image_url_formatter][version] = "1.4"

projects[imce][version] = "1.10"

projects[jquery_update][version] = "2.7"

projects[ldap][version] = "1.0-beta14"

projects[libraries][version] = "2.3"

projects[link][version] = "1.4"

projects[linkit][version] = "3.5"

projects[menu_block][version] = "2.7"

projects[metatag][version] = "1.20"

projects[migrate][version] = "2.8"

projects[migrate_d2d][version] = "2.1"
projects[migrate_d2d][patch][] = "https://www.drupal.org/files/issues/migrate_d2d-menu_names_and_cleanup-1489858-11.patch"

projects[module_filter][version] = "2.0"

projects[oauth][version] = "3.2"

projects[panels_bootstrap_layouts][version] = "3.0"

projects[panels_bootstrap_styles][version] = "1.0-alpha1"

projects[panels_mini_ipe][version] = "1.0-beta4"

projects[path_breadcrumbs][version] = "3.3"

projects[pathauto][version] = "1.3"

projects[pathologic][version] = "3.1"

projects[recaptcha][version] = "2.2"

projects[r4032login][version] = "1.8"

projects[redirect][version] = "1.0-rc3"

projects[restrict_password_change][version] = "1.0-beta2"

projects[role_delegation][version] = "1.1"

projects[rules][version] = "2.9"
projects[rules][patch][] = "https://www.drupal.org/files/issues/rules-fix-fatal-error-features-revert-2186363-2.patch"

projects[strongarm][version] = "2.0"

projects[token][version] = "1.6"

projects[twitter][version] = "5.11"
projects[twitter][patch][] = "https://www.drupal.org/files/issues/twitter-doubleclass-2661088-5.patch"

projects[views][version] = "3.14"

projects[views_tree][version] = "2.0"

projects[webform][version] = "4.14"

projects[wysiwyg_filter][version] = "1.6-rc3"
projects[wysiwyg_filter][patch][] = "https://www.drupal.org/files/issues/wysiwyg_filter-Bypass-rules-835202-16.D7.patch"

; Themes
projects[bootstrap][version] = "3.8"

