; This file was auto-generated by drush make
core = 7.x
api = 2

projects[auto_nodetitle][version] = "1.0"
projects[auto_nodetitle][patch][] = "https://www.drupal.org/files/issues/auto_nodetitle-dont_double_escape_titles-565922-39-against-1.0-stable.patch"

projects[autologout][version] = "4.5"

projects[backup_migrate][version] = "3.4"

projects[bootstrap_fieldgroup][version] = "1.2"

projects[calendar][version] = "3.5"
projects[calendar][patch][] = "https://www.drupal.org/files/issues/calendar-no_results-2489146-1-D7.patch"

projects[captcha][version] = "1.5"

projects[cck][version] = "3.0-alpha3"

projects[ckeditor][version] = "1.17"

projects[ckeditor_link][version] = "2.4"

projects[config_perms][version] = "2.2"

projects[crumbs][version] = "2.5"

projects[css_injector][version] = "1.10"

projects[ctools][version] = "1.14"
projects[ctools][patch][] = "https://www.drupal.org/files/issues/views_panes-more_link_text-1000146-25.patch"

projects[datalayer][version] = "1.x-dev"

projects[date][version] = "2.9"

projects[devel][version] = "1.5"

projects[diff][version] = "3.2"

projects[drafty][version] = "1.0-rc1"

projects[ds][version] = "2.15"

projects[ds_bootstrap_layouts][version] = "3.1"

projects[email][version] = "1.3"

projects[entity][version] = "1.9"

projects[entityreference][version] = "1.5"

projects[facebook_pixel][version] = "1.1"

projects[faq][version] = "1.1"

projects[features][version] = "2.10"

projects[feeds][version] = "2.0-beta3"

projects[field_collection][version] = "1.0-beta11"

projects[field_collection_tabs][version] = "1.1"

projects[field_collection_bootstrap_tabs][version] = "1.x"
projects[field_collection_bootstrap_tabs][type] = "module"
projects[field_collection_bootstrap_tabs][download][type] = "git"
projects[field_collection_bootstrap_tabs][download][url] = "https://git.drupal.org/sandbox/osman/2464117.git"

projects[field_group][version] = "1.5"

projects[field_permissions][version] = "1.0"

projects[field_validation][version] = "2.6"

projects[filebrowser][version] = "3.3"

projects[filefield_sources][version] = "1.11"

projects[flag][version] = "3.9"

projects[flood_control][version] = "1.0"

projects[fontawesome][version] = "2.6"

projects[google_analytics][version] = "2.3"

projects[google_tag][version] = "1.3"
projects[google_tag][patch][] = "https://www.drupal.org/files/issues/2911657_variable_php_error.patch"

projects[hide_submit][version] = "2.4"

projects[image_url_formatter][version] = "1.4"

projects[imce][version] = "1.10"

projects[imce_mkdir][version] = "1.0"

projects[import_html][version] = "1.0"

projects[jquery_update][version] = "2.7"

projects[js_injector][version] = "2.1"

projects[ldap][version] = "2.2"

projects[libraries][version] = "2.3"

projects[link][version] = "1.4"

projects[linkchecker][version] = "1.2"

projects[linkit][version] = "3.5"

projects[login_destination][version] = "1.1"

projects[mailsystem][version] = "2.34"

projects[masquerade][version] = "1.0-rc7"

projects[media][version] = "2.1"

projects[media_flickr][version] = "1.0-alpha4"

projects[menu_block][version] = "2.7"

projects[menu_breadcrumb][version] = "1.5"

projects[metatag][version] = "1.21"

projects[migrate][version] = "2.8"

projects[migrate_d2d][version] = "2.1"
projects[migrate_d2d][patch][] = "https://www.drupal.org/files/issues/migrate_d2d-menu_names_and_cleanup-1489858-11.patch"

projects[mimemail][version] = "1.0-beta4"

projects[module_filter][version] = "2.0"

projects[module_missing_message_fixer][version] = "1.2"

projects[mpac][version] = "1.2"

projects[node_clone][version] = "1.0-rc2"

projects[oauth][version] = "3.3"

projects[page_title][version] = "2.7"

projects[panelizer][version] = "3.1"

projects[panels][version] = "3.8"

projects[panels_bootstrap_layouts][version] = "3.0"

projects[panels_bootstrap_styles][version] = "1.x-dev"

projects[panels_mini_ipe][version] = "1.0-beta4"

projects[path_breadcrumbs][version] = "3.3"

projects[path_redirect_import][version] = "1.0-rc4"

projects[pathauto][version] = "1.3"

projects[pathologic][version] = "3.1"

projects[print][version] = "2.0"

projects[profile2][version] = "1.3"

projects[r4032login][version] = "1.8"

projects[realname][version] = "1.2"

projects[recaptcha][version] = "2.2"

projects[redirect][version] = "1.0-rc3"

projects[references][version] = "2.1"

projects[restrict_password_change][version] = "1.0-beta2"

projects[role_delegation][version] = "1.1"

projects[rules][version] = "2.9"
projects[rules][patch][] = "https://www.drupal.org/files/issues/rules-fix-fatal-error-features-revert-2186363-2.patch"

projects[scanner][version] = "1.0-beta1"

projects[services][version] = "3.20"

projects[siteimprove][version] = "1.0"

projects[strongarm][version] = "2.0"

projects[system_status][version] = "3.1"

projects[token][version] = "1.6"

projects[twitter][version] = "5.11"
projects[twitter][patch][] = "https://www.drupal.org/files/issues/twitter-doubleclass-2661088-5.patch"

projects[uuid][version] = "1.0"

projects[view_unpublished][version] = "1.2"

projects[views][version] = "3.17"

projects[views_bulk_operations][version] = "3.3"

projects[views_data_export][version] = "3.1"

projects[views_php][version] = "1.0-alpha1"

projects[views_tree][version] = "2.0"

projects[webform][version] = "4.14"

projects[workbench][version] = "1.2"

projects[workbench_moderation][version] = "3.0"

projects[workbench_email][version] = "3.12"

projects[wysiwyg_filter][version] = "1.6-rc3"
projects[wysiwyg_filter][patch][] = "https://www.drupal.org/files/issues/wysiwyg_filter-Bypass-rules-835202-16.D7.patch"

; Themes
projects[bootstrap][version] = "3.8"

