<?php
/**
 * @file
 * Drupal needs this blank file.
 */
function ug_moderation_enable() {
	$rid = array_search('authenticated user', user_roles());
	$permissions = array('bypass workbench moderation');
	user_role_revoke_permissions($rid, $permissions);
}

function ug_moderation_disable() {
	$rid = array_search('authenticated user', user_roles());
	$permissions = array('bypass workbench moderation');
	user_role_grant_permissions($rid, $permissions);
}