<div id="ug-footer-global">
  <div class="container">
    <footer class="row navbar navbar-inverse">
      <div class="col-lg-12">
        <ul class="nav navbar-nav navbar-right">
          <li><a href="//www.uoguelph.ca/accessibility/"><span class="fa fa-wheelchair"></span> Accessibility</a></li>
          <li><a href="//www.uoguelph.ca/web/privacy/"><span class="fa fa-key"></span> Privacy</a></li>
          <li><a href="//www.uoguelph.ca/sitemap/"><span class="fa fa-sitemap"></span> Site Map</a></li>
          <li><a href="//www.uoguelph.ca/web/terms/">© University of Guelph</a></li>
        </ul>
      </div>
    </footer>
  </div>
</div>
