<div id="ug-header"><div class="container"> 
  <!-- Static navbar -->
  <nav class="navbar navbar-default navbar-static-top" role="navigation">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="http://www.uoguelph.ca/"><img alt="University of Guelph" src="//www.uoguelph.ca/img/universityofguelph.gif"></a>
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#ug-navbar" aria-expanded="false" aria-controls="navbar"> <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
      </div>
      <div id="ug-navbar" class="navbar-collapse collapse" tabindex="-1">
        <ul class="nav navbar-nav navbar-right navbar-small">
          <li><a href="https://mail.uoguelph.ca/"><span class="glyphicon glyphicon-envelope fa-fw" aria-hidden="true"></span> GryphMail</a></li>
          <li><a href="https://courselink.uoguelph.ca/"><span class="glyphicon glyphicon-pencil fa-fw" aria-hidden="true"></span> CourseLink</a></li>
          <li><a href="//www.uoguelph.ca/directory/"><span class="glyphicon glyphicon-user fa-fw" aria-hidden="true"></span> Directory <span class="sr-only">for University of Guelph</span></a></li>
          <li><a href="//www.lib.uoguelph.ca"><span class="glyphicon glyphicon-book fa-fw" aria-hidden="true"></span> Library</a></li>
          <li><a href="//www.uoguelph.ca/campus/map/"><span class="glyphicon glyphicon-road fa-fw" aria-hidden="true"></span> Maps</a></li>
      <li><a href="//webadvisor.uoguelph.ca/"><span class="glyphicon glyphicon-list-alt fa-fw" aria-hidden="true"></span> WebAdvisor</a></li>
          <li><a href="http://weather.gc.ca/city/pages/on-5_metric_e.html"><span class="glyphicon glyphicon-cloud fa-fw" aria-hidden="true"></span> <span class="sr-only">Guelph </span>Weather</a></li>

        </ul>


        <form class="navbar-form navbar-right" role="form" id="searchbox_011117603928904778939:tp3ks5ha2dw" name="searchform" action="//www.uoguelph.ca/search/">
          <input type="hidden" name="commonname" class="search1" id="searchtext2">
          <input type="hidden" name="vl(freeText0)" class="search1" id="searchtext3">
          <input type="hidden" name="cx" value="011117603928904778939:tp3ks5ha2dw">
          <input type="hidden" name="cof" value="FORID:11">
          <input type="hidden" name="orgstatus" value="all">
          <input type="hidden" name="search" value="simple">
          <input type="hidden" name="mail" value="">
          <input type="hidden" name="phone" value="">
          <input type="hidden" name="department" value="null">
          <input type="hidden" name="showresults" value="yes">
          <input type="hidden" name="givenname" value="">
          <input type="hidden" name="surname" value="">
          <input type="hidden" id="mode" name="mode" value="Basic">
          <input type="hidden" id="tab" name="tab" value="default_tab">
          <input type="hidden" id="indx" name="indx" value="1">
          <input type="hidden" id="dum" name="dum" value="true">
          <input type="hidden" name="srt" value="rank" id="str">
          <input type="hidden" id="vid" name="vid" value="GUELPH">
          <input type="hidden" id="frbg" name="frbg" value="">
          <label id="searchtextlabel" for="searchtext" class="sr-only">Search University of Guelph</label>
          <div class="input-group">
            <input class="form-control search1" placeholder="Search U of G" name="q" type="text" size="20" maxlength="256" id="searchtext">
            <span class="input-group-btn">
            <button class="btn btn-default" id="searchsubmit" type="submit" name="submit" value="search" onclick="javascript: this.form.elements['commonname'].value = this.form.elements['q'].value; this.form.elements['vl(freeText0)'].value = this.form.elements['q'].value;"><span class="glyphicon glyphicon-search" aria-hidden="true"></span><span class="sr-only">Search</span></button>
            </span> </div>
        </form>

        <ul id="globalnav" class="nav navbar-nav navbar-right nav-clear">

          <li class="dropdown"> <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Academics <span class="sr-only">at University of Guelph</span> <span class="caret"></span></a>
            <ul class="dropdown-menu navbar-default dropdown-menu-left" role="menu">
              <li><a href="//www.uoguelph.ca/admissions/">Undergraduate Admissions</a></li>
              <li><a href="//www.uoguelph.ca/graduatestudies/">Graduate Studies</a></li>
              <li><a href="http://opened.uoguelph.ca/en/Distance-Education.asp">Distance Education</a></li>
              <li><a href="//www.uoguelph.ca/registrar/calendars/">Academic Calendars</a></li>
              <li class="divider"></li>
              <li><a href="//www.uoguelph.ca/arts">College of Arts</a></li>
              <li><a href="//www.uoguelph.ca/cbs/">College of Biological Science</a></li>
              <li><a href="//www.uoguelph.ca/business/">College of Business &amp; Economics</a> </li>
              <li><a href="//www.uoguelph.ca/cpes/">College of Physical &amp; Engineering Science</a></li>
              <li><a href="//www.uoguelph.ca/csahs/">College of Social &amp; Applied Human Sciences</a></li>
              <li><a href="//www.uoguelph.ca/oac/">Ontario Agricultural College</a></li>
              <li><a href="//www.ovc.uoguelph.ca/">Ontario Veterinary College</a></li>
              <li class="divider"></li>
              <li><a href="http://www.ridgetownc.uoguelph.ca/">Ridgetown Campus</a></li>
              <li><a href="http://www.guelphhumber.ca/">University of Guelph-Humber</a></li>
            </ul>
          </li>

          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">About <span class="sr-only">University of Guelph </span><span class="caret"></span></a>
            
            <ul class="dropdown-menu navbar-default dropdown-menu-left" role="menu">
              <li><a href="//www.uoguelph.ca/about.html">About the University</a></li>
                          <li class="divider"></li>
              <li><a href="//www.uoguelph.ca/secretariat/office-services/board-governors">Board of Governors</a></li>
              <li><a href="//www.uoguelph.ca/secretariat/office-services/senate">Senate</a></li>
              <li><a href="//www.uoguelph.ca/info/senioradmin">Senior Administration</a></li>
            </ul>
            </li>

         <!-- <li class="dropdown"> <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Info For<span class="caret"></span></a>
            <ul class="dropdown-menu navbar-default dropdown-menu-left" role="menu">
        <li><a href="http://www.uoguelph.ca/applying/">Future Students</a></li>
                <li><a href="http://www.uoguelph.ca/students/">Current Students</a></li>
                <li><a href="http://www.uoguelph.ca/faculty/">Faculty &amp; Staff</a></li>
                <li><a href="http://www.alumni.uoguelph.ca/">Alumni &amp; Friends</a></li>
                <li><a href="http://www.cecs.uoguelph.ca/">Co-op &amp; Employers</a></li>
                <li><a href="http://www.uoguelph.ca/cpa/media/">Media</a></li>
            </ul>
          </li> -->

          <!-- <li><a href="/campus/">Community</a></li> -->
          <li><a href="//www.uoguelph.ca/international/">International</a></li>
          <li><a href="//www.uoguelph.ca/president/">President</a></li>

          <!-- <li class="dropdown"> <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Leadership <span class="caret"></span></a>
            <ul class="dropdown-menu navbar-default" role="menu">
              <li><a href="http://www.uoguelph.ca/president/">President</a></li>
              <li><a href="http://www.uoguelph.ca/vpacademic/">Provost and Vice-President (Academic)</a></li>
              <li><a href="http://www.uoguelph.ca/research/people/vpresearch">Vice-President (Research and External Partnerships)</a></li>
              <li><a href="http://www.uoguelph.ca/vpfinanceadmin/">Vice-President (Finance, Administration and Risk)</a></li>
              <li><a href="http://www.uoguelph.ca/secretariat/office-services/board-governors">Board of Governors</a></li>
              <li><a href="http://www.uoguelph.ca/secretariat/office-services/senate">Senate</a></li>
              <li class="divider"></li>
              <li><a href="/info/senioradmin">Senior Administration</a></li>
            </ul>
          </li> -->

          <li><a href="http://www.uoguelph.ca/research/">Research <span class="sr-only">at University of Guelph</span></a></li>

          <li class="dropdown"> <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Services <span class="sr-only">at University of Guelph </span><span class="caret"></span></a>
            <ul class="dropdown-menu navbar-default" role="menu">
              <li><a href="http://gryphons.ca/">Athletics</a></li>
              <li><a href="//www.bookstore.uoguelph.ca">Bookstore</a></li>
              <li><a href="//www.uoguelph.ca/police/">Campus Community Police</a></li>
              <li><a href="//www.uoguelph.ca/ccs/">Computing & Communications Services</a></li>
              <li><a href="//www.hospitality.uoguelph.ca">Hospitality Services</a></li>
              <li><a href="//www.uoguelph.ca/hr/">Human Resources</a></li>
              <li><a href="//www.uoguelph.ca/studentaffairs/">Student Affairs</a></li>
              <li><a href="//www.housing.uoguelph.ca">Student Housing Services</a></li>
              <li class="divider"></li>
              <li><a href="//www.uoguelph.ca/services/">More Services</a></li>
            </ul>
          </li>
        </ul>
        
      </div>
      <!--/.nav-collapse --> 
    </div>
    <!--/.container-fluid --> 
  </nav>
</div></div>
<!-- /container -->
