<?php

function ug_bredge_add_js() {
  $name = 'ug_bredge_autopilot_url';
  $default = '//cdn.bc0a.com/autopilot/f00000000209359/autopilot_sdk.js';
  $data = variable_get($name, $default);
  $options = array('weight' => '-1000', 'type' => 'external');
  drupal_add_js($data, $options);
}

function ug_bredge_block_info() {    
  $blocks['ug_bredge'] = array(
    // info: The name of the block.
    'info' => t('Brightedge Links'),
    'weight' => 40,
    'status' => TRUE,
    'region' => 'coda',
  );
  return $blocks;
}

function ug_bredge_block_view($delta = '') {
  switch ($delta) {
    case 'ug_bredge':
      $block['subject'] = null;
      $block['content'] = '<div class="be-ix-link-block"><!--Link Block Target Div--></div>';
      ug_bredge_add_js();
      break;
   }
  return $block;
}

